### ISSUE TITLE
Invalid path error when --project option is missing

### ISSUE THREAD

**Issue by wespen** [forfuturellc/apidoc-openapi#3]
When you try to call CLI without the -p parm like  
```npx apidoc-openapi --src ./src/api/ --out ./docs/api.json```  

you get back
```The "path" argument must be of type string. Received undefined```

The problem is in line 44 with path.resolve
```apidoc: path.resolve(cwd, program.project)```

Stack:
```javascript
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.resolve (path.js:980:7)
    at Object.main (/node_modules/@forfuture/apidoc-openapi/src/index.js:44:18)
```

Let me know if you would accept the pull request.

**Comment by GochoMugo** [comment]
It surely is **not** clear that the parameter is required.

What changes do you suggest?

**Comment by wespen** [comment]
Handle it as optional and skip path resolving.
apidoc is in if case later in the code.

**Comment by GochoMugo** [comment]
Defaults added in https://github.com/forfuturellc/apidoc-openapi/commit/6b20c1560f848e6a746bea8dac8309174bd9d8ab.

* `--project` defaults to `apidoc.json` in current working directory.
* `--src` defaults to current working directory
